{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.uk-taniyama.quack",
    "module": "quack-serialization",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "quack-serialization-1.0.1-SNAPSHOT.jar",
          "url": "quack-serialization-1.0.1-SNAPSHOT.jar",
          "size": 15386,
          "sha512": "3e3c039fd405d6e37d5e0736b3242ec25ff3c6fdb59c0c3f40986d1dac5e8e43a9eb2ad2ad1c27e8b5c3ff7f01bb1070936675282a611ac33abcd8872a33eb4d",
          "sha256": "4286a89e7c545aa789c3478f0d2d10d333ac109b1458c9dd520bb6d455925e80",
          "sha1": "f4ab2a78cc7fcdd64afcbb871d395156cd84a8b6",
          "md5": "2b9800173cee31c486cf0d70fa754285"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.uk-taniyama.quack",
          "module": "quack-java",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "quack-serialization-1.0.1-SNAPSHOT.jar",
          "url": "quack-serialization-1.0.1-SNAPSHOT.jar",
          "size": 15386,
          "sha512": "3e3c039fd405d6e37d5e0736b3242ec25ff3c6fdb59c0c3f40986d1dac5e8e43a9eb2ad2ad1c27e8b5c3ff7f01bb1070936675282a611ac33abcd8872a33eb4d",
          "sha256": "4286a89e7c545aa789c3478f0d2d10d333ac109b1458c9dd520bb6d455925e80",
          "sha1": "f4ab2a78cc7fcdd64afcbb871d395156cd84a8b6",
          "md5": "2b9800173cee31c486cf0d70fa754285"
        }
      ]
    }
  ]
}
