{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.uk-taniyama.quack",
    "module": "quack-java",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "quack-java-1.0.0-SNAPSHOT.jar",
          "url": "quack-java-1.0.0-SNAPSHOT.jar",
          "size": 54896,
          "sha512": "4eb97dd5e649d648d7632e3d0f3c4cb9b1f3e7a507021899e74264f8792a5526d37f5516d9fc0cf9923d372aa450fe7a5663c28d1e5b500676db8a2fc4b4423d",
          "sha256": "d1fb3d3f3eec0e9bc95d8e99440f149164acd4cb051e24ba925d9d1f0ec844c8",
          "sha1": "705675370b5a56e85fe3c72663c86336c7b74eff",
          "md5": "d6fc9cb3b5077d5e2ef33482842f0502"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "quack-java-1.0.0-SNAPSHOT.jar",
          "url": "quack-java-1.0.0-SNAPSHOT.jar",
          "size": 54896,
          "sha512": "4eb97dd5e649d648d7632e3d0f3c4cb9b1f3e7a507021899e74264f8792a5526d37f5516d9fc0cf9923d372aa450fe7a5663c28d1e5b500676db8a2fc4b4423d",
          "sha256": "d1fb3d3f3eec0e9bc95d8e99440f149164acd4cb051e24ba925d9d1f0ec844c8",
          "sha1": "705675370b5a56e85fe3c72663c86336c7b74eff",
          "md5": "d6fc9cb3b5077d5e2ef33482842f0502"
        }
      ]
    }
  ]
}
