{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.uk-taniyama.quack",
    "module": "quack-java",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "quack-java-1.0.1-SNAPSHOT.jar",
          "url": "quack-java-1.0.1-SNAPSHOT.jar",
          "size": 57739,
          "sha512": "3483899061c5d3dcd8d30acf8b5c3b00f2aa03bc2d42775574d75afa46a2b0f67b1965a5f2e4f01c9297c8170c787cc031c4daf89393449ed13372e87354a837",
          "sha256": "a330eb39bf2763a216f99ec4a64a34501e61b249c777b5922681d722caeeb99f",
          "sha1": "6588890b9e2c3f7a67d2f28c8007aecb06554d6f",
          "md5": "1eeb4c40b409c5e5b5de003bfb91d33b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "quack-java-1.0.1-SNAPSHOT.jar",
          "url": "quack-java-1.0.1-SNAPSHOT.jar",
          "size": 57739,
          "sha512": "3483899061c5d3dcd8d30acf8b5c3b00f2aa03bc2d42775574d75afa46a2b0f67b1965a5f2e4f01c9297c8170c787cc031c4daf89393449ed13372e87354a837",
          "sha256": "a330eb39bf2763a216f99ec4a64a34501e61b249c777b5922681d722caeeb99f",
          "sha1": "6588890b9e2c3f7a67d2f28c8007aecb06554d6f",
          "md5": "1eeb4c40b409c5e5b5de003bfb91d33b"
        }
      ]
    }
  ]
}
